Updating twitter user table username example
Updating example from `id` to `username` in the 2nd example.  ID is used in the where clause for the 1st example, 2nd example is searching for the username.

test:

> select
  *
from
  twitter_user
where
  id = 'turbothq'
Error: twiiter callout status 400 Invalid Request:One or more parameters to your request was invalid.


> select
  *
from
  twitter_user
where
  username = 'turbothq'
+------------+--------+----------+---------------------+--------------------------------------------------------------------------->
| id         | name   | username | created_at          | description                                                               >
+------------+--------+----------+---------------------+--------------------------------------------------------------------------->
| 2469180332 | Turbot | turbothq | 2014-04-29 11:53:47 | Get cloud work done with Turbot. Creators of https://t.co/cvetkFJXNk and h>
|            |        |          |                     |                                                                           >
|            |        |          |                     |